version: "3.7"

services:
  client-request-emmiter:
    container_name: client-request-emmiter.php-cli
    build:
      context: client-request-emmiter/docker
      dockerfile: php-cli/Dockerfile
    volumes:
      - ./client-request-emmiter:/app
    tty: true
    depends_on:
      - rabbitmq

  client-request-processor:
    container_name: client-request-processor.worker
    build:
      context: client-request-processor/docker
      dockerfile: php-cli/Dockerfile
    volumes:
      - ./client-request-processor:/app
      - ./client-request-processor/docker/supervisord/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./client-request-processor/docker/supervisord/supervisord-programs.conf:/etc/supervisor/conf.d/app.conf
    command: [ "supervisord", "-c", "/etc/supervisor/supervisord.conf" ]
    tty: true
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: queue.rabbitmq
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672